### ISSUE TITLE
Crash with LibrarianLib

### ISSUE THREAD

**Issue by Robolightning** [ChAoSUnItY/Forgelin-Continuous#11]
librarianlib version: 1.12.2-4.22
Forgelin Continuous version: 1.9.23.2
Full logs:
[debug.log](https://github.com/ChAoSUnItY/Forgelin-Continuous/files/15057667/debug.log)
[latest.log](https://github.com/ChAoSUnItY/Forgelin-Continuous/files/15057668/latest.log)
[crash-2024-04-22_07.29.16-client.txt](https://github.com/ChAoSUnItY/Forgelin-Continuous/files/15057670/crash-2024-04-22_07.29.16-client.txt)

**Comment by ChAoSUnItY** [comment]
This is due to outdated compiled version of LibrarianLib and its dependency, which breaks internal method invocation convention.

This will not be fixed in Forgelin-Continuous. A possible way to resolve this issue is to recompile LibrarianLib with recent version, but lots of breaking changes would be expected.

**Comment by Robolightning** [comment]
> This is due to outdated compiled version of LibrarianLib and its dependency, which breaks internal method invocation convention.
> 
> This will not be fixed in Forgelin-Continuous. A possible way to resolve this issue is to recompile LibrarianLib with recent version, but lots of breaking changes would be expected.

Maybe you, or somebody you know, may do the new fork of LibrarianLib for this?

**Comment by ChAoSUnItY** [comment]
As far as I'm aware of, LibrarianLib is not easy to be ported to latest version of kotlin in order to adapt Forgelin-Continuous, and [author already stated this situation](https://github.com/TeamWizardry/LibrarianLib/issues/176#issuecomment-979693245).

**Comment by ChAoSUnItY** [comment]
Update: We introduced a separate build (namely [LibrarianLib-Continuous](https://www.curseforge.com/minecraft/mc-mods/librarianlib-continuous)) that is compatible with Forgelin-Continuous. This issue is now fully resolved.
