### ISSUE TITLE
Incompatible with LibrarianLib

### ISSUE THREAD

**Issue by UnpeelableBanana** [ChAoSUnItY/Forgelin-Continuous#12]
I use librarianlib for wizardry and an additional mod. I cannot load in with the Divine Favor mod which is dependent on this mod because librarian lib is dependent on the old Forgelin. I have tried running just this, running just old forgelin, running just librarianlib and none of these worked. The crash happens on startup.

**Comment by ChAoSUnItY** [comment]
This issue had been already discussed in #11.
