### ISSUE TITLE
Server Crash with DustyDataSync Mod in RLCraft Dregora

### ISSUE THREAD

**Issue by Jenzoga** [ChAoSUnItY/Forgelin-Continuous#18]
Hi,

# Server Crash with DustyDataSync Mod in RLCraft Dregora

## Environment
- Modpack: RLCraft Dregora 1.0.3
- Server Capacity: 30 players

-  Suspected Mods: 
  - Dusty Data Sync (dusty_data_sync)
  - Forge Mod Loader (FML)
  - Minecraft Forge (forge)
  - FastWorkbench (fastbench)

## Current Setup
We are running multiple servers to handle player load and using DustyDataSync to synchronize player data across servers.

## Issue
The server crashes immediately when players attempt to connect after implementing DustyDataSync.

## Steps to Reproduce
1. Set up RLCraft Dregora server
2. Install DustyDataSync Mod
3. Replace LibrarianLib-Continuous and Forgelin-Continuous
4. Attempt player connection

## Additional Context
- Original server was experiencing significant lag with 30 players
- Implementation goal was to distribute player load across multiple servers

## Crash Log
[crash-2024-11-08_11.18.53-server.txt](https://github.com/user-attachments/files/17672996/crash-2024-11-08_11.18.53-server.txt)

Please let me know if you need any additional details or clarification.

**Comment by ChAoSUnItY** [comment]
I am a little confused if this crash is even caused by either FC or LLC or both, it seems to me that this is probably not directly caused by FC, can you test it by running with only DDS and FC?

**Comment by Jenzoga** [comment]
good point. let me check.

**Comment by Jenzoga** [comment]
if I only install DDS and FC, The client will clash. and this is the log https://mclo.gs/DuViU1E

**Comment by ChAoSUnItY** [comment]
This is a issue related to Bountiful itself, you should remove entries that contains items from removed mods in `config/bountiful/rewards.json`, see ejektaflex/Bountiful#88 for more info.

Additionally, this shouldn't happen as you mentioned that you only installed DDS and FC, can you clearify?

**Comment by Jenzoga** [comment]
This is a issue related to Bountiful itself, you should remove entries that contains items from removed mods in config/bountiful/rewards.json, see https://github.com/ejektaflex/Bountiful/issues/88 for more info.
`I will check this.`

Additionally, this shouldn't happen as you mentioned that you only installed DDS and FC, can you clearify? 
` - now i underrstand what you mean. I thought you mean remove LLC. I will try only installed DDS and FC and test my environment`

will update you again and thank you.

**Comment by Jenzoga** [comment]
you are right. i removed issue items in config/bountiful/rewards.json and the client is no longer crash. thank you for point out.

For the server, Now i only only installed DDS and FC. and it is crashed.

[crash-2024-11-12_20.39.31-server.txt](https://github.com/user-attachments/files/17717420/crash-2024-11-12_20.39.31-server.txt)

**Comment by ChAoSUnItY** [comment]
This have nothing to do with FC, DDS didn't pack slf4j into its jar, please report this in DDS's repo.

**Comment by Jenzoga** [comment]
thank you so much
