### ISSUE TITLE
Missing Kotlin dependencies

### ISSUE THREAD

**Issue by Bluexin** [ChAoSUnItY/Forgelin-Continuous#2]
It seems since version 1.6.20.0 of this mod the Kotlin libraries are not included anymore
```
$ jar tf ./Forgelin-Continuous-1.7.20.0.jar | wc -l
14
$ jar tf ./Forgelin-Continuous-1.6.10.0.jar | wc -l
2992
$ jar tf ./Forgelin-Continuous-1.7.20.0.jar
META-INF/
META-INF/MANIFEST.MF
io/
io/github/
io/github/chaosunity/
io/github/chaosunity/forgelin/
io/github/chaosunity/forgelin/preloader/
io/github/chaosunity/forgelin/preloader/ForgelinPlugin.class
io/github/chaosunity/forgelin/preloader/ForgelinSetup.class
io/github/chaosunity/forgelin/Forgelin.class
io/github/chaosunity/forgelin/ForgelinAutomaticEventSubscriber.class
io/github/chaosunity/forgelin/KotlinAdapter.class
META-INF/Forgelin-Continuous.kotlin_module
mcmod.info
```
You can also see on CF the file sizes went down big time : 
![image](https://user-images.githubusercontent.com/8713616/232254022-a9a05533-75d4-47c1-9f00-69c8d7268bbc.png)

Am I missing something ?

**Comment by Bluexin** [comment]
I cloned the project and built it, it included all the classes. Not sure what's up with the versions on CF

**Comment by ChAoSUnItY** [comment]
Oops, I found out that it's probably the building workflow I'm using is wrong (which only calls `jar` task but `shadowJar` task), I'll reupload the latest (1.7.20), versions between 1.6.20 and 1.7.20 will mark as invalid builds.

**Comment by ChAoSUnItY** [comment]
Now the fixed version of 1.7.20 is published as version 1.7.20.0.

**Comment by Bluexin** [comment]
Thanks. It still does not include coroutines right ?
I made a custom build including coroutines 1.6.4 (and `no_coroutines = false`) which works, after I changed the dependency on `kotlinx-coroutines-core` to `kotlinx-coroutines-core-jvm`
Any chance to get this included as well ? I can make a PR for it if you prefer.

**Comment by ChAoSUnItY** [comment]
> Thanks. It still does not include coroutines right ? I made a custom build including coroutines 1.6.4 (and `no_coroutines = false`) which works, after I changed the dependency on `kotlinx-coroutines-core` to `kotlinx-coroutines-core-jvm` Any chance to get this included as well ? I can make a PR for it if you prefer.

No, 1.7.20.1 is now including coroutines, you can directly use CF version without any worry.

**Comment by Bluexin** [comment]
Thanks !
